ALTER TABLE PostTag
DROP CONSTRAINT FK_PostTag_Tag;

ALTER TABLE PostTag
ADD CONSTRAINT FK_PostTag_Tag
FOREIGN KEY (TagId)
REFERENCES Tag(Id)
ON DELETE CASCADE;

ALTER TABLE BlogTag
DROP CONSTRAINT FK_BlogTag_Tag;

ALTER TABLE BlogTag
ADD CONSTRAINT FK_BlogTag_Tag
FOREIGN KEY (TagId)
REFERENCES Tag(Id)
ON DELETE CASCADE;

ALTER TABLE AuthorTag
DROP CONSTRAINT FK_AuthorTag_Tag;

ALTER TABLE AuthorTag
ADD CONSTRAINT FK_AuthorTag_Tag
FOREIGN KEY (TagId)
REFERENCES Tag(Id)
ON DELETE CASCADE;